export const SET_APP_LANGUAGE = 'SET_APP_LANGUAGE';

// USER SESSION
export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_RESPONSE = 'SIGNUP_RESPONSE';
export const SET_USER = 'SET_USER';
export const SET_PASSWORD = 'SET_PASSWORD';
export const SET_PROFILEIMAGE = 'SET_PROFILEIMAGE';
export const SET_PREFERENCE = 'SET_PREFERENCE';
export const IS_ONBOARDING_VISITED = 'IS_ONBOARDING_VISITED';
export const GUEST_USER = 'GUEST_USER'

// LOGOUT 
export const LOGOUT = 'LOGOUT'